<?php

namespace Database\Seeders\Training;

use App\Models\Tenant;
use App\Models\Training\TrainingCourse;
use App\Models\Training\TrainingLesson;
use App\Models\Training\TrainingModule;
use App\Models\Training\TrainingQuiz;
use App\Models\Training\TrainingQuizQuestion;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * The shipped onboarding curriculum.
 *
 * Written out as data rather than generated by factories: a trainer
 * opening the Academy for the first time should find a real, coherent
 * course they can run — not lorem ipsum. Everything is idempotent on
 * (tenant, slug) / (course, title) so re-running only fills gaps.
 *
 * Video URLs point at Google's public sample clips, used purely as
 * placeholders so the player is demonstrably working. No copyrighted
 * training footage ships with this.
 */
class TrainingContentSeeder extends Seeder
{
    public const SAMPLE_VIDEO = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4';

    public const COURSE_SLUG = 'fynnedge-sales-executive-onboarding';

    /**
     * module title => [lesson titles]
     *
     * @var array<string, list<string>>
     */
    public const CURRICULUM = [
        'Company Introduction' => [
            'Who we are and what we do',
            'How the loan distribution business works',
        ],
        'FYNN-ON Overview' => [
            'Touring the FYNN-ON dashboard',
            'Leads, customers and applications',
        ],
        'Loan Products' => [
            'The product catalogue at a glance',
            'Matching a customer to a product',
        ],
        'Personal Loan' => [
            'Eligibility and documentation',
            'Common personal loan objections',
        ],
        'Home Loan' => [
            'Property and income checks',
            'Sanction to disbursal timeline',
        ],
        'Business Loan' => [
            'Assessing a business borrower',
            'Turnover, vintage and banking',
        ],
        'Customer Qualification' => [
            'Reading a salary slip',
            'Building a qualification checklist',
        ],
        'Lead Calling' => [
            'Opening a call that does not get cut',
            'Qualifying in ninety seconds',
        ],
        'Documentation' => [
            'The standard document set',
            'Rejections caused by paperwork',
        ],
        'Bank Eligibility' => [
            'Reading a lender policy grid',
            'Choosing the right lender first time',
        ],
        'Lead Management' => [
            'Working your pipeline daily',
            'When to drop a lead',
        ],
        'Follow-up Process' => [
            'Scheduling and honouring follow-ups',
            'Keeping a warm lead warm',
        ],
        'Customer Handling' => [
            'Handling an anxious customer',
            'Escalations and who owns them',
        ],
        'Disbursal' => [
            'From sanction letter to credit',
            'Post-disbursal responsibilities',
        ],
        'Final Assessment' => [
            'What the assessment covers',
        ],
    ];

    public function run(): void
    {
        $this->seedFor(Tenant::production());
    }

    public function seedFor(Tenant $tenant): TrainingCourse
    {
        $course = TrainingCourse::updateOrCreate(
            [
                'tenant_id' => $tenant->getKey(),
                'slug' => self::COURSE_SLUG,
            ],
            [
                'title' => 'FynnEdge Sales Executive Onboarding',
                'summary' => 'Everything a new sales executive needs before their first live call.',
                'description' => 'A fifteen-module onboarding programme covering the company, the '
                    .'product suite, customer qualification, calling, documentation, lender '
                    .'eligibility, pipeline management and disbursal — ending in a graded '
                    .'assessment.',
                'level' => 'beginner',
                'status' => 'published',
                'duration_minutes' => 15 * 60,
                'pass_percentage' => 70,
            ]
        );

        $this->seedModules($course);
        $this->seedFinalAssessment($course);

        return $course;
    }

    protected function seedModules(TrainingCourse $course): void
    {
        $moduleOrder = 0;

        foreach (self::CURRICULUM as $moduleTitle => $lessonTitles) {
            $moduleOrder++;

            $module = TrainingModule::updateOrCreate(
                [
                    'training_course_id' => $course->getKey(),
                    'title' => $moduleTitle,
                ],
                [
                    'description' => "Module {$moduleOrder} of the onboarding programme.",
                    'sort_order' => $moduleOrder,
                    'status' => 'published',
                ]
            );

            $lessonOrder = 0;

            foreach ($lessonTitles as $lessonTitle) {
                $lessonOrder++;

                // Every third lesson is a video, so the player, the
                // reading view and the mixed case are all represented.
                $isVideo = $lessonOrder % 3 === 0 || $moduleOrder % 3 === 0;

                $lesson = TrainingLesson::updateOrCreate(
                    [
                        'training_module_id' => $module->getKey(),
                        'title' => $lessonTitle,
                    ],
                    [
                        'summary' => Str::finish($lessonTitle, '.'),
                        'content' => $this->lessonBody($moduleTitle, $lessonTitle),
                        'content_type' => $isVideo ? 'video' : 'text',
                        'video_url' => $isVideo ? self::SAMPLE_VIDEO : null,
                        'duration_minutes' => $isVideo ? 12 : 8,
                        'sort_order' => $lessonOrder,
                        'is_required' => true,
                        'status' => 'published',
                    ]
                );

                // One quiz per module, hung off its first lesson.
                if ($lessonOrder === 1 && $moduleTitle !== 'Final Assessment') {
                    $this->seedLessonQuiz($lesson, $moduleTitle);
                }
            }
        }
    }

    protected function lessonBody(string $moduleTitle, string $lessonTitle): string
    {
        return implode("\n\n", [
            "{$lessonTitle} — part of the {$moduleTitle} module.",
            'By the end of this lesson you should be able to explain the topic to a customer '
                .'in plain language, know which questions to ask, and know where in FYNN-ON to '
                .'record what you learn.',
            'Key points:',
            "• Why this matters on a live call.\n"
                ."• The two or three facts you must always capture.\n"
                ."• The most common mistake new joiners make here.\n"
                .'• Where this shows up later in the customer journey.',
            'Work through the material, then take the module quiz. You need 60% to pass, and '
                .'you have three attempts.',
        ]);
    }

    protected function seedLessonQuiz(TrainingLesson $lesson, string $moduleTitle): void
    {
        $quiz = TrainingQuiz::updateOrCreate(
            [
                'quizzable_type' => TrainingLesson::class,
                'quizzable_id' => $lesson->getKey(),
                'kind' => TrainingQuiz::KIND_QUIZ,
            ],
            [
                'title' => "{$moduleTitle} Quiz",
                'description' => "Check your understanding of {$moduleTitle}.",
                'pass_percentage' => 60,
                'time_limit_minutes' => 10,
                'max_attempts' => 3,
                'status' => 'published',
            ]
        );

        foreach ($this->questionsFor($moduleTitle) as $order => $question) {
            TrainingQuizQuestion::updateOrCreate(
                [
                    'training_quiz_id' => $quiz->getKey(),
                    'question' => $question['question'],
                ],
                [
                    'type' => 'single_choice',
                    'options' => $question['options'],
                    'correct_answer' => $question['correct'],
                    'explanation' => $question['explanation'],
                    'marks' => 1,
                    'sort_order' => $order + 1,
                ]
            );
        }
    }

    /**
     * @return list<array{question: string, options: array<string, string>, correct: list<string>, explanation: string}>
     */
    protected function questionsFor(string $moduleTitle): array
    {
        return [
            [
                'question' => 'A customer wants a personal loan. What should the sales executive check first?',
                'options' => [
                    'A' => "The customer's favourite bank",
                    'B' => 'Income and eligibility',
                    'C' => "The customer's preferred colour",
                    'D' => 'Office location only',
                ],
                'correct' => ['B'],
                'explanation' => 'Eligibility comes first — everything else follows from whether the case can be funded at all.',
            ],
            [
                'question' => "Where should a new lead's details be recorded?",
                'options' => [
                    'A' => 'In a personal notebook',
                    'B' => 'In a WhatsApp message to your team leader',
                    'C' => 'In FYNN-ON, against the lead record',
                    'D' => 'Nowhere until the customer confirms',
                ],
                'correct' => ['C'],
                'explanation' => 'A lead that is not in the system cannot be followed up, reported on, or credited to you.',
            ],
            [
                'question' => "What is the correct response when a customer's documents are incomplete?",
                'options' => [
                    'A' => 'Submit anyway and hope it passes',
                    'B' => 'Log the pending document and follow up before submitting',
                    'C' => 'Cancel the lead',
                    'D' => 'Ask a colleague to sign for them',
                ],
                'correct' => ['B'],
                'explanation' => 'Incomplete files are the single largest cause of avoidable rejections.',
            ],
            [
                'question' => "Which of these belongs in the module's follow-up discipline?",
                'options' => [
                    'A' => 'Calling only when you have spare time',
                    'B' => 'Recording a next follow-up date on every open case',
                    'C' => 'Waiting for the customer to call you',
                    'D' => 'Closing the lead after one missed call',
                ],
                'correct' => ['B'],
                'explanation' => 'Every open case carries a dated next action — that is what keeps the pipeline alive.',
            ],
            [
                'question' => "What does '{$moduleTitle}' primarily help you do?",
                'options' => [
                    'A' => 'Fill in reports faster',
                    'B' => 'Serve the customer correctly at that stage of the journey',
                    'C' => 'Avoid speaking to customers',
                    'D' => 'Skip the documentation step',
                ],
                'correct' => ['B'],
                'explanation' => 'Every module maps onto one stage of the customer journey.',
            ],
        ];
    }

    protected function seedFinalAssessment(TrainingCourse $course): void
    {
        $assessment = TrainingQuiz::updateOrCreate(
            [
                'quizzable_type' => TrainingCourse::class,
                'quizzable_id' => $course->getKey(),
                'kind' => TrainingQuiz::KIND_ASSESSMENT,
            ],
            [
                'title' => 'Final Assessment',
                'description' => 'The graded assessment covering the whole onboarding programme.',
                'pass_percentage' => 70,
                'time_limit_minutes' => 45,
                'max_attempts' => 2,
                'status' => 'published',
            ]
        );

        foreach ($this->assessmentQuestions() as $order => $question) {
            TrainingQuizQuestion::updateOrCreate(
                [
                    'training_quiz_id' => $assessment->getKey(),
                    'question' => $question['question'],
                ],
                [
                    'type' => 'single_choice',
                    'options' => $question['options'],
                    'correct_answer' => $question['correct'],
                    'explanation' => $question['explanation'],
                    'marks' => 2,
                    'sort_order' => $order + 1,
                ]
            );
        }
    }

    /**
     * @return list<array{question: string, options: array<string, string>, correct: list<string>, explanation: string}>
     */
    protected function assessmentQuestions(): array
    {
        return [
            [
                'question' => 'Put the customer journey in order.',
                'options' => [
                    'A' => 'Lead → Customer → Application → Sanction → Disbursal',
                    'B' => 'Application → Lead → Disbursal → Customer',
                    'C' => 'Customer → Disbursal → Lead → Application',
                    'D' => 'Sanction → Lead → Customer → Application',
                ],
                'correct' => ['A'],
                'explanation' => 'This is the ladder every case climbs, and the order FYNN-ON models.',
            ],
            [
                'question' => 'A salaried customer earns ₹45,000 a month. What matters most next?',
                'options' => [
                    'A' => 'Their existing obligations and employer category',
                    'B' => 'Their date of birth only',
                    'C' => 'Which branch is nearest to them',
                    'D' => 'Nothing — salary alone decides eligibility',
                ],
                'correct' => ['A'],
                'explanation' => 'Net take-home after obligations, plus employer category, drives the eligible amount.',
            ],
            [
                'question' => 'A lender rejects a file for an incorrect employer category. Whose responsibility was that check?',
                'options' => [
                    'A' => 'The lender',
                    'B' => 'The customer',
                    'C' => 'The sales executive, before login',
                    'D' => 'Nobody — it is unavoidable',
                ],
                'correct' => ['C'],
                'explanation' => 'Category is checked against the lender grid before a file is logged in.',
            ],
            [
                'question' => 'When should a follow-up date be set?',
                'options' => [
                    'A' => 'Only after the customer asks for one',
                    'B' => 'On every open lead and customer, every time you touch it',
                    'C' => 'Once a month',
                    'D' => 'Never — follow-ups are the team leader\'s job',
                ],
                'correct' => ['B'],
                'explanation' => 'An open case without a next action is an abandoned case.',
            ],
            [
                'question' => 'What must never be shared outside the company?',
                'options' => [
                    'A' => 'The product brochure',
                    'B' => 'Customer documents and personal data',
                    'C' => 'Your own contact number',
                    'D' => 'The office address',
                ],
                'correct' => ['B'],
                'explanation' => 'Customer data is confidential and regulated — it stays inside the system.',
            ],
            [
                'question' => 'A customer is anxious about a delayed disbursal. What is the correct first step?',
                'options' => [
                    'A' => 'Stop answering their calls',
                    'B' => 'Promise a date you cannot confirm',
                    'C' => 'Check the current status in FYNN-ON and tell them exactly where it stands',
                    'D' => 'Tell them to contact the bank directly',
                ],
                'correct' => ['C'],
                'explanation' => 'Accurate status beats reassurance; the system is the source of truth.',
            ],
            [
                'question' => 'Which record proves a case was actually funded?',
                'options' => [
                    'A' => 'The lead remark',
                    'B' => 'The sanction letter',
                    'C' => 'The disbursal entry with the LAN number',
                    'D' => 'The first call log',
                ],
                'correct' => ['C'],
                'explanation' => 'Sanction is approval; disbursal with a LAN is money actually credited.',
            ],
            [
                'question' => 'What is the purpose of the pending-document field?',
                'options' => [
                    'A' => 'To track exactly what is still owed by the customer',
                    'B' => 'To store internal notes',
                    'C' => 'To record the lender name',
                    'D' => 'It has no purpose',
                ],
                'correct' => ['A'],
                'explanation' => 'It is what turns "the file is stuck" into a specific, chaseable list.',
            ],
        ];
    }
}
